#!/bin/sh -x

test $# -eq 1
test -f $1
OF=$(df | grep resin | tail -n 1 | cut -d ' ' -f1 | grep -oP '[^\d]*')
for dev in $(df | grep resin | cut -d ' ' -f1); do umount $dev; done
dd if=$1 bs=1M | pv -fs $(ls -l $1 | cut -d ' ' -f5) | sudo dd of=$OF bs=1M
