#!/bin/sh

HTTP_DIR=/srv/http

#YOCTO_TMP_DIR=/home/willpnw/dev-projects/tablesafe/rail-reve/ts-yocto/devops-rail/rail/yocto/build/tmp-glibc
#YOCTO_SOURCES_DIR=/home/willpnw/dev-projects/tablesafe/rail-reve/ts-yocto/devops-rail/rail/yocto/build/workspace/sources
#YOCTO_IMAGES_DIR=${YOCTO_TMP_DIR}/deploy/images
#YOCTO_WORK_DIR=${YOCTO_TMP_DIR}/work/cortexa9t2hf-neon-oe-linux-gnueabi
#LINUX_BOOT_DIR=/home/willpnw/dev-projects/tablesafe/rail-reve/rail-linux-4.x/linux-4.9.46/arch/arm/boot
#TFTP_DIR=/srv/tftp

rm /tmp/watches
srcToDest() {
    /home/willpnw/dotfiles/scripts/fileCopy ${1} ${2} &
    echo "/home/willpnw/dotfiles/scripts/fileCopy ${1} ${2}" >> /tmp/watches
}

#srcToDest /run/media/willpnw/0e2c99c8-efcc-40c3-a2da-c98791650611/schneider/buildroot/output/target/usr/bin/simple_opengl /srv/http/simple_opengl

#srcToDest ${LINUX_BOOT_DIR}/zImage ${TFTP_DIR}/zImage
#bcm958300k.dtb
#for dtb in tablesafe-rail_A10.dtb tablesafe-rail_A11.dtb; do
	#srcToDest ${LINUX_BOOT_DIR}/dts/${dtb} /srv/tftp/zImage.dtb &
#done

#srcToDest ${YOCTO_IMAGES_DIR}/tablesafe-a10/u-boot-dtb.img ${TFTP_DIR}/uboot
#srcToDest ${YOCTO_IMAGES_DIR}/tablesafe-a10/bin.boot1-tablesafe_rail-a10 ${TFTP_DIR}/boot1
#srcToDest ${YOCTO_IMAGES_DIR}/tablesafe-a10/bin.boot1-bcm958303k_pos_sa ${TFTP_DIR}/boot1

#srcToDest ${YOCTO_TMP_DIR}/deploy/images/tablesafe-a10/ota.tar.gz                   ${HTTP_DIR}/rail/ota/ota_01-08-00-000-0-A.tar.gz
#srcToDest ${YOCTO_WORK_DIR}/provision/1.0-r0/build/provision                        ${HTTP_DIR}/provision
#srcToDest ${YOCTO_WORK_DIR}/athena/1.0-r0/package/usr/bin/athena                     ${HTTP_DIR}/athena
#srcToDest ${YOCTO_WORK_DIR}/msr-test/1.0-r0/msr-test-1.0/msr-test                    ${HTTP_DIR}/msr-test
#srcToDest ${YOCTO_WORK_DIR}/pin-entry-test/1.0-r0/pin-entry-test-1.0/pin-entry-test  ${HTTP_DIR}/pin-entry-test
#srcToDest ${YOCTO_WORK_DIR}/qt-5.6.3-demo/1.0-r0/build/qt-5.6.3-demo                ${HTTP_DIR}/qt-5.6.3-demo
#srcToDest ${YOCTO_WORK_DIR}/mesa/2_19.0.1-r0/build/lib/libEGL.so.1.0.0              ${HTTP_DIR}/libEGL.so.1.0.0
#srcToDest ${YOCTO_WORK_DIR}/mesa/2_19.0.1-r0/sysroot-destdir/usr/lib/dri/vc4_dri.so ${HTTP_DIR}/vc4_dri.so
#srcToDest ${YOCTO_WORK_DIR}/ota/1.0-r0/recipe-sysroot/ota/ota                       ${HTTP_DIR}/ota
#srcToDest ${YOCTO_SOURCES_DIR}/ota/rail-ux/ota/ota/ota.sh                           ${HTTP_DIR}/ota.sh
#srcToDest ${YOCTO_SOURCES_DIR}/ota/rail-ux/ota/ota/reve-map.json                    ${HTTP_DIR}/reve-map.json
#srcToDest ${YOCTO_SOURCES_DIR}/ota/rail-ux/ota/ota/reve-utils.sh                    ${HTTP_DIR}/reve-utils.sh

#RAIL_UX_REVD_DIR=/home/willpnw/dev-projects/tablesafe/rail-revd/rail/rail-ux
#srcToDest ${RAIL_UX_REVD_DIR}/build-ota-bcm-arm/ota         ${HTTP_DIR}/rail/ota/ota/
#srcToDest ${RAIL_UX_REVD_DIR}/ota/ota/files/ota.sh          ${HTTP_DIR}/rail/ota/ota/
#srcToDest ${RAIL_UX_REVD_DIR}/ota/ota/files/armv6l-map.json ${HTTP_DIR}/rail/ota/ota/
#srcToDest ${RAIL_UX_REVD_DIR}/ota/ota/files/armv6l-utils.sh ${HTTP_DIR}/rail/ota/ota/
#srcToDest ${RAIL_UX_REVD_DIR}/ota/ota/files/armv7l-map.json ${HTTP_DIR}/rail/ota/ota/
#srcToDest ${RAIL_UX_REVD_DIR}/ota/ota/files/armv7l-utils.sh ${HTTP_DIR}/rail/ota/ota/

#srcToDest ${RAIL_UX_REVD_DIR}/ota/ota/files/armv7l-utils.sh ${HTTP_DIR}/rail/ota/ota/

LEARY_KERNEL=/run/media/willpnw/c472ae24-dac4-4f3c-872b-0eacc8383e5d/leary/whl-dbe2/poky/build/tmp/deploy/images/whleary-64/bzImage
srcToDest ${LEARY_KERNEL} ${HTTP_DIR}/vmlinuz


