#!/bin/bash
set -e

cd ~/Rail/rail
if [[ "$(git describe --abbrev=0)" > "1-07-27-086" ]]; then
    echo "Builing with linaro"
    case $1 in
        a)
            TOOLCHAIN=codeSourcery PLATFORM=A6 VARIANT=F make rail-ux.athena && cp /home/will/Rail/rail-ux/build-athena-bcm-arm/athena /srv/http/
            ;;
        p)
            TOOLCHAIN=codeSourcery PLATFORM=A6 VARIANT=F make rail-ux.provision && cp /home/will/Rail/rail-ux/build-provision-bcm-arm/provision /srv/http/
            ;;
        c)
            TOOLCHAIN=codeSourcery PLATFORM=A6 VARIANT=F make rail-ux.chatterclient && cp /home/will/Rail/rail-ux/build-chatterclient-bcm-arm/ChatterClient /srv/http/
            ;;
        s)
            TOOLCHAIN=codeSourcery PLATFORM=A6 VARIANT=F make rail-ux.chatterserver && cp /home/will/Rail/rail-ux/build-chatterserver-bcm-arm/ChatterServer /srv/http/
            ;;
        *)
            echo "Unsupported"
            exit 1
            ;;
    esac
else
    echo "Builing with codeSourcery"
    cd ~/Rail/rail/linux
    source tablesafe.env
    case $1 in
        a)
            VARIANT=F make athena && cp /home/will/Rail/rail-ux/build-athena-bcm-arm/athena /srv/http/
            ;;
        d)
            cd ~/Rail/rail/rail-ux
            make driverstest && cp /home/will/Rail/rail/rail-ux/build-driverstest-bcm-arm/DriversTest /srv/http/
            ;;
        o)
            cd ~/Rail/rail/rail-ux/ota/ota
            PLATFORM=A5 make && cp /home/will/Rail/rail/rail-ux/build-ota-bcm-arm/output/ota.tar /srv/http
            ;;
        n)
            cd ~/Rail/rail/rail-ux
            make networktest && cp /home/will/Rail/rail/rail-ux/build-networktest-bcm-arm/NetworkTest /srv/http/
            ;;
        p)
            cd ~/Rail/rail/rail-ux
            make provision && cp /home/will/Rail/rail/rail-ux/build-provision-bcm-arm/provision /srv/http/
            ;;
        s)
            cd ~/Rail/rail/rail-ux
            make splash
            ;;
    esac
fi

