#!/bin/bash
mkdir -p /opt/build
pushd /opt/build
kill $(ps aux | grep '[o]pt' | awk '{print $2}')
touch /opt/rail/rail-ux/athena/ota.qrc
qmake /opt/rail/rail-ux/athena/ota.pro -r -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug
make
popd
